Repository Berkmann18/nclr, pull requests merged in 2023-05, with the labels that each got.

#109 Try with --color=16m
  index.js
  package.json
  symbols.js
  test/index.test.js
  test/symbols.test.js
Labels: needs-more-info, Type: Maintenance :construction:, Status: In Review :detective:, PR: unreviewed, Priority: Critical

#956 Upgrade: Package upgrades
  package-lock.json
  package.json
Labels: Type: Maintenance :construction:, Priority: Critical

#958 Fix: Dep vulnerabilities + dep updates
  .husky/pre-commit
  package-lock.json
  package.json
Labels: Type: Vulnerability :warning:, Type: Maintenance :construction:
